#!/usr/bin/env node
// Generates a fresh EVM keypair and a fresh Tezos ed25519 keypair and writes them to .env.
// Refuses to overwrite an existing .env unless --force is passed.
import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { ed25519 } from "@noble/curves/ed25519.js";
import { secp256k1 } from "@noble/curves/secp256k1.js";
import { blake2b } from "@noble/hashes/blake2b.js";
import { sha256 } from "@noble/hashes/sha256.js";
import { keccak_256 } from "@noble/hashes/sha3.js";

const ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

function base58(bytes) {
  let n = 0n;
  for (const b of bytes) n = (n << 8n) | BigInt(b);
  let out = "";
  while (n > 0n) {
    out = ALPHABET[Number(n % 58n)] + out;
    n /= 58n;
  }
  for (const b of bytes) {
    if (b !== 0) break;
    out = "1" + out;
  }
  return out;
}

function b58check(prefix, payload) {
  const data = new Uint8Array([...prefix, ...payload]);
  const check = sha256(sha256(data)).slice(0, 4);
  return base58(new Uint8Array([...data, ...check]));
}

const hex = (u8) => "0x" + Buffer.from(u8).toString("hex");

// EVM (secp256k1)
const evmPriv = new Uint8Array(randomBytes(32));
const evmPubUncompressed = secp256k1.getPublicKey(evmPriv, false).slice(1); // drop 0x04
const evmAddress = "0x" + Buffer.from(keccak_256(evmPubUncompressed).slice(-20)).toString("hex");

// Tezos (ed25519)
const seed = new Uint8Array(randomBytes(32));
const tzPub = ed25519.getPublicKey(seed);
const edsk = b58check([43, 246, 78, 7], new Uint8Array([...seed, ...tzPub])); // 64-byte secret
const edpk = b58check([13, 15, 37, 217], tzPub);
const tz1 = b58check([6, 161, 159], blake2b(tzPub, { dkLen: 20 }));

const envPath = new URL("../.env", import.meta.url);
if (existsSync(envPath) && !process.argv.includes("--force")) {
  console.error(".env already exists; pass --force to overwrite");
  process.exit(1);
}

writeFileSync(
  envPath,
  [
    "# Generated by scripts/gen-keys.mjs. Previewnet only. Never commit.",
    `EVM_PRIVATE_KEY=${hex(evmPriv)}`,
    `EVM_ADDRESS=${evmAddress}`,
    `TEZOS_SECRET_KEY=${edsk}`,
    `TEZOS_PUBLIC_KEY=${edpk}`,
    `TEZOS_ADDRESS=${tz1}`,
    "",
  ].join("\n"),
);

console.log(`EVM_ADDRESS=${evmAddress}`);
console.log(`TEZOS_ADDRESS=${tz1}`);
console.log(`TEZOS_PUBLIC_KEY=${edpk}`);
